AWSTemplateFormatVersion: "2010-09-09"
Description: "Main stack for VPC Infrastructure"

Parameters:
  VpcCidr:
    Type: String
    Default: "10.0.0.0/16"
    Description: CIDR block for VPC

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "./modules/vpc.yaml"
      Parameters:
        VpcCIDR: !Ref VpcCidr

  InternetGatewayStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: "./modules/internet-gateway.yaml"
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        Name: "my-igw"

Outputs:
  VpcId:
    Description: VPC ID
    Value: !GetAtt VPCStack.Outputs.VpcId

  InternetGatewayId:
    Description: Internet Gateway ID
    Value: !GetAtt InternetGatewayStack.Outputs.InternetGatewayId
