AWSTemplateFormatVersion: "2010-09-09"
Description: "Main stack for VPC Infrastructure"

Parameters:
  VpcCidr:
    Type: String
    Default: "10.0.0.0/16"
    Description: CIDR block for VPC

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "./modules/vpc.yaml"
      Parameters:
        VpcCIDR: !Ref VpcCidr

Outputs:
  VpcId:
    Description: VPC ID
    Value: !GetAtt VPCStack.Outputs.VpcId
