AWSTemplateFormatVersion: "2010-09-09"
Description: "Private Route Table Module"

Parameters:
  VpcId:
    Type: String
    Description:

  NATGatewayId:
    Type: String
    Description:

  SubnetId:
    Type: String
    Description:

  Name:
    Type: String
    Description:

Resources:
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Ref Name

  RouteNATGateway:
    Type: AWS::EC2::Route
    DependsOn: PrivateRouteTable
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      NatGatewayId: !Ref NATGatewayId

  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn: PrivateRouteTable
    Properties:
      SubnetId: !Ref SubnetId
      RouteTableId: !Ref PrivateRouteTable

Outputs:
  PrivateRouteTableId:
    Description: ID of the created Private Route Table
    Value: !Ref PrivateRouteTable
    Export:
      Name: !Sub ${AWS::StackName}-PrivateRouteTable
