AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 Instance"

Parameters:
  VpcId:
    Type: String
    Description:

  PublicSecurityGroupId:
    Type: String
    Description: ID of the public security group allowed to SSH

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupName: private-sg
      GroupDescription: Allow SSH only from public SG

      SecurityGroupIngress:
        - CidrIp: !Ref AllowedSSHIp
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
          SourceSecurityGroupId: !Ref PublicSecurityGroupId

      SecurityGroupEgress:
        - IpProtocol: "-1"
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0

      Tags:
        - Key: Name
          Value: public-sg

Outputs:
  PrivateSGId:
    Value: !Ref SecurityGroup
