name: Terraform CI/CD

on:
  push:
    paths:
      - 'Terraform/**'
      - '.github/workflows/terraform.yml'

jobs:
  terraform_ci:
    name: Terraform Security Scan & Deployment
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python for Checkov
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Checkov
        run: pip install -q checkov

      - name: Run Checkov on Terraform code
        run: checkov -d Terraform/ -s

      - name: Get public IP of GitHub runner
        run: |
          echo "MY_IP=$(curl -s https://checkip.amazonaws.com)/32" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init Plan Apply and Test
        run: |
          cd Terraform
          terraform init
          terraform plan -var="allowed_ssh_ip=${{ env.MY_IP }}" -out=tfplan
          terraform apply -auto-approve tfplan
          bash ../test_infra.sh terraform
          terraform destroy -var="allowed_ssh_ip=${{ env.MY_IP }}"
 
